# Generated by Django 4.2.5 on 2023-09-13 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_i_halarmodel_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='i̇halarmodel',
            name='uye',
        ),
        migrations.CreateModel(
            name='İhaUyeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('ihalar', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='home.i̇halarmodel')),
                ('uye', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İHA',
                'verbose_name_plural': 'İHALAR',
                'ordering': ['-id'],
            },
        ),
    ]
