# Generated by Django 4.2.5 on 2023-09-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_i_halarmodel_uye_i_hauyemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='i̇hauyemodel',
            options={'ordering': ['-id'], 'verbose_name': 'uye ihaları', 'verbose_name_plural': 'uye ihaları'},
        ),
    ]
