# Generated by Django 4.2.5 on 2023-09-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_i_hauyemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='i̇halarmodel',
            name='fiyat',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
