# Generated by Django 4.2.5 on 2023-09-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_i_halarmodel_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇halarmodel',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
