# Generated by Django 4.2.5 on 2023-09-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_i_halarmodel_resim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'kategoriler',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='i̇halarmodel',
            name='marka',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='i̇halarmodel',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
