# Generated by Django 4.2.5 on 2023-09-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_kategoriler_i_halarmodel_marka_i_halarmodel_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriler',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kategoriler',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default='2023-09-13 16:33:28.03741+03'),
            preserve_default=False,
        ),
    ]
