# Generated by Django 4.2.5 on 2023-09-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_i_halarmodel_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇halarmodel',
            name='fiyat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
